### ISSUE TITLE
Conda Environment Config Very Slow, Need Lightweight Versions

### ISSUE THREAD

**Issue by ericspod** [Project-MONAI/MONAI#5088]
**Is your feature request related to a problem? Please describe.**
The included Conda specification file `environment-dev.yml` is very slow to resolve packages, taking 12 minutes on a reasonably modern workstation with the latest conda libraries. The mlflow, einops, and transformers libraries appear to be the main culprits. For slightly older versions of conda or some other environment change the package resolution may not complete at all. 

**Describe the solution you'd like**
A simpler dev YAML file with optional luxuries stripped out would be more convenient for quick setup. Additionally a separate file for a minimal environment, and a runtime environment without development libraries, would be nice. This however introduces the need to make sure newly added dependencies are added to all files, but we have this issue with the requirements-*.txt files already.

**Describe alternatives you've considered**
Installing things manually.

**Additional context**

Minimal environment:

```yaml
name: monai
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - numpy>=1.17
  - pytorch>=1.6
  - cudatoolkit=11.6
```

Runtime environment:

```yaml
name: monai
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - numpy>=1.17
  - pytorch>=1.6
  - setuptools>=50.3.0,!=60.0.0
  - ignite==0.4.8
  - gdown>=4.4.0
  - scipy
  - nibabel
  - pillow!=8.3.0  # https://github.com/python-pillow/Pillow/issues/5571
  - scikit-image>=0.14.2
  - tqdm>=4.47.0
  - python-lmdb
  - torchvision
  - psutil
  - pandas
  - requests
  - einops  # slow
  - transformers  # slow
  - pyyaml
  - fire
  - jsonschema
  - pynrrd
  - pydicom
  - h5py
  - pip
  - pip:
    # pip for itk as conda-forge version only up to v5.1
    - itk>=5.2
    # OS-specific needs to be done via pip:
    #   https://github.com/conda/conda/issues/8089
    - openslide-python==1.1.2
    - cucim>=21.8.2; platform_system == "Linux"
    - imagecodecs; platform_system == "Linux"
    - tifffile; platform_system == "Linux"
    - matplotlib!=3.5.0
```
