### ISSUE TITLE
'epochs' parameter for `ShuffleBuffer`

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5488]
**Is your feature request related to a problem? Please describe.**
when creating a shuffled iterable dataset

```yaml
cache_datasets:
  - _target_: ShuffleBuffer
    data:
      _target_: CacheDataset
      data: "@datalist"
      transform: $@preprocessing.set_random_state(123)
      hash_as_key: true
    seed: 1
```
the `ShuffleBuffer` supports only a single epoch of `datalist`
would be great to add `epochs` argument to the class for multiple epochs or infinite epochs.

Alternative solutions are:

- extending the data list: `monai.data.utils.resample_datalist(@datalist, epochs)`
- using the itertools: `itertools.cycle(@data)`

both solutions are not efficiently using the iterator.
